name: .net CI/CD

on:
  push:
    branches:
      - master
    
    tags:
      - 'v*'
permissions:
 contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build Application
        run: |
         dotnet build --configuration Release

      - name: Run Tests
        run: |
         dotnet test --no-build --configuration Release

      - name: Publish
        run: |
         dotnet publish -c Release -o publish

      - name: Get version
          id: version
          run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Zip
          run: zip -r myapp-${{ env.VERSION }}.zip publish/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: app
          path: publish/
      

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/**
  deploy:
   needs: build
   runs-on: ubuntu-latest

   steps:
    - name: Deploy
      run: echo "Deploying application...."
  
